### ISSUE TITLE
IFC Optimizer : Layer name (IFCPRESENTATIONLAYERWITHSTYLE) missing after optimization

### ISSUE THREAD

**Issue by MichaelVictoriano** [youshengCode/IfcToolbox#4] opened 2021-11-10 21:52 UTC
The Layer name of the object was removed after the IFC files has been Optimised. Am I missing some settings prior to running the app by its default settings?

![image](https://user-images.githubusercontent.com/81650759/141199391-2bfd7802-f260-445e-b0b0-3b0916b22c9f.png)

**Comment by youshengCode** [comment] 2021-11-10 22:23
Hi Michael, thanks for your report. 

For the layer info, it's kind of weird... Because the optimizer only takes care of duplicated IFC instances or the points in the geometry. Could you provide a small test file to allow us to test and debug?

And for the second one. It's the name of the parser IFC. Because we need to fill in this information every time we write a new file (IfcOptimizer is rewriting a new IFC actually). So for now, I'm using the product name here. Maybe what I could do is add a new option in configuration, maybe like 'keep the old origination system' and copy the old info and rewrite after the optimization process. I think it will be fine for your case.

**Comment by youshengCode** [comment] 2021-11-13 02:07
@MichaelVictoriano I changed using the original OriginatingSystem as default, it seems like this will be more natural for the user. Thanks for your feedback.

It's already modified in this repo, you can process it directly with code from the examples folder.
The GUI app in the Microsoft Store will be modified for the next release. 

I can't reproduce the layer info missing issue until you provide me with a small simple file.
So, I will close this issue for now. Thanks again.

**Closed by youshengCode** 2021-11-13 02:07 UTC
Labels: enhancement

**Comment by MichaelVictoriano** [comment] 2021-11-15 18:28
@youshengCode Apologies for the delay as I was a little bit swapped.
[Files.zip](https://github.com/youshengCode/IfcToolbox/files/7540842/Files.zip)

I have uploaded 2 files; (1) the Original IFC file & the other is the (2) Optimised IFC files.

The file was optimized by 4.5%.
![image](https://user-images.githubusercontent.com/81650759/141834664-f999f44f-821d-4a95-8b29-27e742af7d45.png)

Below is the setting I used.
![image](https://user-images.githubusercontent.com/81650759/141834761-e5ac440f-75ad-49f7-8827-d6d4eb1ab0c2.png)

As mentioned, after the optimization. IFCPRESENTATIONLAYERWITHSTYLE was missing.

Thank you for your help and hard work.

**Comment by youshengCode** [comment] 2021-11-15 21:49
Hi @MichaelVictoriano, 
I think I have found the problem, but honestly, I think I could not fix it quickly.

The IfcOptimizer in IfcToolbox is written with an algorithm in Xbim lib called `InsertCopy`. And as I said earlier, we are creating a new IFC file. Because in the backend, we take each IfcProduct as the main object and copy it one by one in the new IFC file with all its referenced entities. For example, for an IfcWall, we will copy the IfcWall entity, and all its material, properties, color, quantities, all related to this IfcWall entity. In this way, we could leave all information which not been referenced in the old file and create a new one without redundancy information. 

In your case, this entity actually is not referenced by any other entity. 

![image](https://user-images.githubusercontent.com/30289753/141855135-68751611-7041-4345-aefe-3849dfac2358.png)

And I think this is coming from the Xbim lib, cause IfcToolbox is just a higher-level implementation. Maybe I will try to make a pull request in Xbim lib to fix this problem at the lib level. But it could take some time with their next release. Hope you can understand that.

By the way, I highly recommend you to use the `Keep old reference label` as `Off` for the configuration. Cause the id of entities will not affect the actual information and it will provide a better optimization result. 
Here is a result with the same file you provided.

![image](https://user-images.githubusercontent.com/30289753/141857982-3db222e0-d740-4d57-ad34-d5139353b5a6.png)

I will let you know if we fixed this in the future with maybe a new version of Xbim lib.
