### ISSUE TITLE
IFC Relocator crash

### ISSUE THREAD

**Issue by raswart** [youshengCode/IfcToolbox#2] opened 2021-09-06 15:09 UTC
When using "Align automatic" to update the IFC Project Coordinate the application crashes.

Tried with multiple source IFC files

**Comment by youshengCode** [comment] 2021-09-07 10:32
Hi, could you try to "Clean cache" from the setting page. And close and reopen the app then try again.
If it's still crash, could you send me a sample file with a screenshot of your configurations selected?
// It's just for test use. If it's a sensible file, you can also send me by mail to ifctoolbox@outlook.com

**Comment by raswart** [comment] 2021-09-07 10:54
Still crashing after "Clean Cache".
I have emailed you the files and settings using WeTransfer

**Comment by youshengCode** [comment] 2021-09-07 14:07
Thank raswart, but for now I have not got nothing in ifctoolbox@outlook.com please make sure you have used the correct address.

**Comment by youshengCode** [comment] 2021-09-07 18:09
@raswart Really thanks for your feedback. It's fixed and will be integrated into the next release. I will let you know when it's online.

**Comment by raswart** [comment] 2021-11-02 08:26
Hi @youshengCode. any updates on this? Just tried to relocate a different project and had the same crash.

**Comment by youshengCode** [comment] 2021-11-03 10:04
Hi @raswart Sorry for the late reply, We are currently struggling with the issue of multilingual versions. It was originally expected to be released together in these two days. Maybe, I could push a new version first that fixes this problem. Then push other versions later. Cause the submission process in the store is really painful... 

Anyway, I will make a submission today. And try to notify you when it's online.

**Comment by youshengCode** [comment] 2021-11-12 19:11
Hi @raswart, there is a little bit of delay caused by the submission process. But eventually, IFC Toolbox version 1.2.0 is online. You can just open the store to update it or use the sideload package here if you can't use the Microsoft store. 
[https://github.com/youshengCode/IfcToolbox/releases/tag/sideload](https://github.com/youshengCode/IfcToolbox/releases/tag/sideload)

Enjoy, and feel free to open an issue if you got other problems.

**Closed by youshengCode** 2021-11-12 19:11 UTC
